jlfblog/articles/urls.py
from django.urls import path
from articles.views import *

app_name = 'articles'
urlpatterns = [
    path('category/<int:categoryid>', categorys, name='category'),
    path('articledetails/<int:articleid>', get_article, name='article_details'),
    path('add_comment/<int:articleid>', add_comment, name='add_comment'),
    path('search/', search_article, name='search_article')
]

jlfblog/jlfblog/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('users/', include('users.urls', namespace='users')),
    path('articles/', include('articles.urls', namespace='articles')),

]

jlfblog/users/urls.py
from django.urls import path
from users.views import user_login, user_register, get_code, user_logout

app_name = 'users'
urlpatterns = [
    path('login/', user_login, name='user_login'),
    path('register/', user_register, name='user_register'),
    path('getcode/', get_code, name='get_code'),
    path('logout/', user_logout, name='user_logout'),
]

jlfblog/templates/article_details.html
<!DOCTYPE HTML>
{% load staticfiles %}
<!--
	Hyperspace by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
    <title>{{ article.title }}</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
    <noscript>
        <link rel="stylesheet" href="{% static 'css/noscript.css' %}"/>
    </noscript>
</head>
<body class="is-preload">

<!-- Header -->
<header id="header">
    <a href="{% url 'index' %}" class="title">Jlfblog</a>
    <nav>
        <ul>
            <li><a href="{% url 'index' %}">首页</a></li>
            {#						<li><a href="{% url 'articles:category' %}"></a></li>#}
        </ul>
    </nav>
</header>

<!-- Wrapper -->
<div id="wrapper">

    <!-- Main -->
    <section id="main" class="wrapper">
        <div class="inner">
            <h1 class="major">{{ article.title }}</h1>
            {#							<span class="image fit"><img src="images/pic04.jpg" alt="" /></span>#}
            <p>作者：{{ article.author.username }}&nbsp;&nbsp;&nbsp;&nbsp;发表时间：{{ article.add_time }}</p>
            <p>{{ article_content|safe }}</p>
    </section>
    <div>
        <h3>评论列表</h3>
        <ul>
            {% if comments %}
                {% for comment in comments %}
                    <li>{{ comment.comment_person }}:{{ comment.comment_content }}</li>
                    <p>{{ comment.comment_time }}</p>
                {% endfor %}
            {% else %}
                <p>暂无评论</p>
            {% endif %}
        </ul>
        {% if request.session.username %}
            <form action="{% url 'articles:add_comment' article.id %}" method="post" id="commentform">
                {% csrf_token %}
                <p><textarea name="comment" id="comment" cols="25" rows="5" tabindex="4"
                             class="message_input"></textarea></p>
                <p>
                    <input name="submit" type="submit" id="submit" tabindex="5" value="提交评论" class="button"/>
                </p>
            </form>
        {% else %}
            请<a href="{% url 'users:user_login' %}">登录</a>后发表评论
        {% endif %}
    </div>
</div>

<!-- Footer -->
<footer id="footer" class="wrapper alt">
    <div class="inner">
        <ul class="menu">
            <li>&copy; Untitled. All rights reserved.</li>
            <li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
        </ul>
    </div>
</footer>

<!-- Scripts -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery.scrollex.min.js' %}"></script>
<script src="{% static 'js/jquery.scrolly.min.js' %}"></script>
<script src="{% static 'js/browser.min.js' %}"></script>
<script src="{% static 'js/breakpoints.min.js' %}"></script>
<script src="{% static 'js/util.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

jlfblog/templates/article_list.html
<!DOCTYPE HTML>
{% load staticfiles %}
<!--
	Hyperspace by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
    <title>{{ category.name }}</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
    <noscript>
        <link rel="stylesheet" href="{% static 'css/noscript.css' %}"/>
    </noscript>
</head>
<body class="is-preload">

<!-- Header -->
<header id="header">
    <a href="{% url 'index' %}" class="title">JLFblog</a>
    <nav>
        <ul>
            <li><a href="{% url 'index' %}">首页</a></li>
        </ul>
    </nav>
</header>

<!-- Wrapper -->
<div id="wrapper">

    <!-- Main -->
    <section id="main" class="wrapper">
        <div class="inner">
            <h1 class="major">{{ category.name }}</h1>

            <!-- Text -->
            {% for article in articles %}
                <section>
                    <h2><a href={% url 'articles:article_details'  article.id %}>{{ article.title }}</a></h2>
                    <p>{{ article.desc }}</p>
                    <p>浏览({{ article.click_num }})&nbsp;&nbsp;评论({{ article.comment_num }})</p>
                </section>
                <hr>
            {% endfor %}


        </div>
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if articles.has_previous %}
                    <li>
                        <a href="{{ category.id }}?page={{ articles.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li>
                        <span aria-hidden="true" class="off">&laquo;</span>
                    </li>
                {% endif %}
                {% for page_num in articles.paginator.page_range %}
                    <li>
                        <a {% ifequal num page_num|stringformat:'i' %}class="on"{% endifequal %}
                           href="{{ category.id }}?page={{ page_num }}">{{ page_num }}</a>
                    </li>
                {% endfor %}
                {% if articles.has_next %}
                    <li>
                        <a href="{{ category.id }}?page={{ articles.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li>
                        <span aria-hidden="true" class="off">&raquo;</span>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </section>

</div>


<!-- Scripts -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery.scrollex.min.js' %}"></script>
<script src="{% static 'js/jquery.scrolly.min.js' %}"></script>
<script src="{% static 'js/browser.min.js' %}"></script>
<script src="{% static 'js/breakpoints.min.js' %}"></script>
<script src="{% static 'js/util.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

jlfblog/templates/index.html
<!DOCTYPE HTML>
{% load staticfiles %}
<html>
<head>
    <title>JLF blog</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
    <noscript>
        <link rel="stylesheet" href="{% static 'css/noscript.css' %}"/>
    </noscript>
</head>
<body class="is-preload">

<!-- Sidebar -->
<section id="sidebar">
    <div class="inner">
        <nav>
            <ul>
                <li><a href="#intro">首页</a></li>
                <li><a href="#one">热门文章</a></li>
                <li><a href="#two">文章分类</a></li>
                <li><a href="#three">关于我</a></li>
            </ul>

        </nav>
    </div>
</section>

<!-- Wrapper -->
<div id="wrapper">

    <!-- Intro -->
    <section id="intro" class="wrapper style1 fullscreen fade-up">
        <div class="inner">
            <h1>JLF blog</h1>
            <p>一个分享编程知识的个人网站，欢迎留言评论</p>
            <ul class="actions">
                {% if request.session.username %}
                    <li>欢迎访问！{{ request.session.username }}</li>
                    <li><a href={% url 'users:user_logout' %}>点击退出</a></li>
                {% else %}
                    <li><a href={% url 'users:user_login' %} class="button scrolly">登录</a></li>
                    <li><a href={% url 'users:user_register' %} class="button scrolly">注册</a></li>
                {% endif %}
            </ul>
            <form method="get" name="form" onsubmit="return beforeSubmit(this);"
                  action="{% url 'articles:search_article' %}">
                <div id="box">
                    <input type="text" name="search" placeholder="输入关键字搜索文章">
                    <input type="submit" id="search1" value="搜索">
                </div>
            </form>
        </div>
    </section>

    <!-- One -->
    <section id="one" class="wrapper style2 spotlights">
        {% for click_obj in click_order %}
            <section>
                {#            <a href="#" class="image"><img src="{{ MEDIA_URL }}{{ click_obj.image }}" alt="" data-position="center center"/></a>#}
                <div class="content">
                    <div class="inner">
                        <h2>{{ click_obj.title }}</h2>
                        <p>{{ click_obj.desc }}</p>
                        <p>浏览({{ click_obj.click_num }})&nbsp;&nbsp;评论({{ click_obj.comment_num }})</p>
                        <ul class="actions">
                            <li><a href="{% url 'articles:article_details' click_obj.id %}" class="button">查看文章</a></li>
                        </ul>
                    </div>
                </div>
            </section>
        {% endfor %}
    </section>

    <!-- Two -->
    <section id="two" class="wrapper style3 fade-up">
        <div class="inner">
            <h2>文章分类</h2>
            <p></p>
            <div class="features">
                <section>
                    <span class="icon major fa-code"></span>
                    <h3><a href={% url 'articles:category' 1 %}?page=1>python基础语法({{ c1 }})</a></h3>
                    <p></p>
                </section>
                <section>
                    <span class="icon major fa-lock"></span>
                    <h3><a href={% url 'articles:category' 2 %}?page=1>Linux操作系统({{ c2 }})</a></h3>
                    <p></p>
                </section>
                <section>
                    <span class="icon major fa-cog"></span>
                    <h3><a href={% url 'articles:category' 3 %}?page=1>数据库常识({{ c3 }})</a></h3>
                    <p></p>
                </section>
                <section>
                    <span class="icon major fa-desktop"></span>
                    <h3><a href={% url 'articles:category' 4 %}?page=1>网络编程及web框架({{ c4 }})</a></h3>
                    <p></p>
                </section>
                <section>
                    <span class="icon major fa-chain"></span>
                    <h3><a href={% url 'articles:category' 5 %}?page=1>python爬虫({{ c5 }})</a></h3>
                    <p></p>
                </section>
                <section>
                    <span class="icon major fa-diamond"></span>
                    <h3><a href={% url 'articles:category' 6 %}?page=1>程序员新闻({{ c6 }})</a></h3>
                    <p></p>
                </section>
            </div>

        </div>
    </section>

    <!-- Three -->
    <section id="three" class="wrapper style1 fade-up">
        <div class="inner">
            <h2>关于我</h2>
            <h3>有问题可联系我的邮箱和电话，也可以在下方留言，收到留言后我会第一时间回复您</h3>
            <p></p>
            <div class="split style1">
                <section>
                    <form method="post" name='board' onsubmit="return leave_message(this)" action="{% url 'index' %}">
                        {% csrf_token %}
                        <div class="fields">
                            <div class="field half">
                                <label for="姓名">Name</label>
                                <input type="text" name="name" id="name"/>
                            </div>
                            <div class="field half">
                                <label for="邮箱">Email</label>
                                <input type="text" name="email" id="email"/>
                            </div>
                            <div class="field">
                                <label for="留言">Message</label>
                                <textarea name="message" id="message" rows="5"></textarea>
                            </div>
                        </div>
                        <ul class="actions">
                            <input type="submit" id="send" value="点击发送">
                        </ul>
                    </form>
                </section>
                <section>
                    <ul class="contact">
                        <li>
                            <h3>地址</h3>
                            <span>成都市双流区</span>
                        </li>
                        <li>
                            <h3>邮箱</h3>
                            <a href="#">18561699217@163.com</a>
                        </li>
                        <li>
                            <h3>电话</h3>
                            <span>+8618561699217</span>
                        </li>
                        {#                        <li>#}
                        {#                            <h3>Social</h3>#}
                        {#                            <ul class="icons">#}
                        {#                                <li><a href="#" class="fa-twitter"><span class="label">Twitter</span></a></li>#}
                        {#                                <li><a href="#" class="fa-facebook"><span class="label">Facebook</span></a></li>#}
                        {#                                <li><a href="#" class="fa-github"><span class="label">GitHub</span></a></li>#}
                        {#                                <li><a href="#" class="fa-instagram"><span class="label">Instagram</span></a></li>#}
                        {#                                <li><a href="#" class="fa-linkedin"><span class="label">LinkedIn</span></a></li>#}
                        {#                            </ul>#}
                        {#                        </li>#}
                    </ul>
                </section>
            </div>
        </div>
    </section>

</div>

<!-- Footer -->
<footer id="footer" class="wrapper style1-alt">
    <div class="inner">
        <ul class="menu">
            <li>&copy; Untitled. All rights reserved.</li>
            <li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
        </ul>
    </div>
</footer>

<!-- Scripts -->
<script type="text/javascript">

    function beforeSubmit(form) {
        //判断是否存在内容
        if (form.search.value == '') {
            alert('请输入关键字');
            //阻止提交表单
            return false;
        }
        return true


    }
</script>
<script>
    function leave_message(board) {
        var reg = new RegExp("^[a-z0-9]+([._\\-]*[a-z0-9])*@([a-z0-9]+[-a-z0-9]*[a-z0-9]+.){1,63}[a-z0-9]+$");
        if (board.name.value == '') {
            alert('请填写姓名');
            return false;
        }
        if (board.email.value == '') {
            alert('请填写邮箱');
            return false;
        } else if (!reg.test(board.email.value)) {
            alert('邮箱格式不正确');
            return false;
        } else {
            if (board.message.value == '') {
                alert('不能发空内容');
                return false;
            }
        }

        alert('发送成功！')
        return true
    }
</script>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery.scrollex.min.js' %}"></script>
<script src="{% static 'js/jquery.scrolly.min.js' %}"></script>
<script src="{% static 'js/browser.min.js' %}"></script>
<script src="{% static 'js/breakpoints.min.js' %}"></script>
<script src="{% static 'js/util.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>


</body>
</html>

jlfblog/templates/search_article_list.html
<!DOCTYPE HTML>
{% load staticfiles %}
<!--
	Hyperspace by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
    <title>搜索结果</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>

    <noscript>
        <link rel="stylesheet" href="{% static 'css/noscript.css' %}"/>
    </noscript>
</head>
<body class="is-preload">

<!-- Header -->
<header id="header">
    <a href="{% url 'index' %}" class="title">JLFblog</a>
    <nav>
        <ul>
            <li><a href="{% url 'index' %}">首页</a></li>
        </ul>
    </nav>
</header>

<!-- Wrapper -->
<div id="wrapper">

    <!-- Main -->
    <section id="main" class="wrapper">
        <div class="inner">
            {% if articles %}
                <h1 class="major">以下是包含{{ keyword }}的文章</h1>
            {% else %}
                <h2 class="major">抱歉，没有关于{{ keyword }}的文章</h2>
            {% endif %}
            <!-- Text -->
            {% for article in articles %}
                <section>
                    <h2><a href={% url 'articles:article_details'  article.id %}>{{ article.title }}</a></h2>
                    <p>{{ article.desc }}</p>
                    <p>浏览({{ article.click_num }})&nbsp;&nbsp;评论({{ article.comment_num }})</p>
                </section>
                <hr>
            {% endfor %}


            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% if articles.has_previous %}
                        <li>
                            <a href="?search={{ keyword }}&page={{ articles.previous_page_number }}"
                               aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li>
                            <span aria-hidden="true" class="off">&laquo;</span>
                        </li>
                    {% endif %}
                    {% for page_num in articles.paginator.page_range %}
                        <li>
                            <a {% ifequal num page_num|stringformat:'i' %}class="on"{% endifequal %}
                               href="?search={{ keyword }}&page={{ page_num }}">{{ page_num }}</a>
                        </li>
                    {% endfor %}
                    {% if articles.has_next %}
                        <li>
                            <a href="?search={{ keyword }}&page={{ articles.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li>
                            <span aria-hidden="true" class="off">&raquo;</span>
                        </li>
                    {% endif %}
                </ul>
            </nav>
    </section>

</div>


<!-- Scripts -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery.scrollex.min.js' %}"></script>
<script src="{% static 'js/jquery.scrolly.min.js' %}"></script>
<script src="{% static 'js/browser.min.js' %}"></script>
<script src="{% static 'js/breakpoints.min.js' %}"></script>
<script src="{% static 'js/util.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>


</body>
</html>

jlfblog/templates/user_login.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
    <link href="{% static 'css/reglogin.css' %}" rel='stylesheet' type='text/css'/>
    <script src="https://cdn.bootcss.com/jquery/2.2.1/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div class="main">
    <div class="header">
        <h1>用户登录</h1>
    </div>
    <p></p>
    <form method="post" action="{% url 'users:user_login' %}">
        {% csrf_token %}
        <ul class="left-form">
            <h2>登录:</h2>
            <li>
                <input type="text" placeholder="Username" name="username"/>
                <a href="#" class="icon ticker"> </a>
                <div class="clear"></div>
            </li>
            <li>
                <input type="password" placeholder="password" name="password"/>
                <a href="#" class="icon into"> </a>
                <div class="clear"></div>
            </li>
            <li>
                <input type="text" placeholder="验证码" name="checkcode" style="width:100px"/>
                <img src="{% url 'users:get_code' %}" id="checkcode">
                <a href="#" class="icon into"> </a>
                <div class="clear"></div>
            </li>
            <input type="submit" value="登录">
            <div class="clear"></div>
        </ul>
        <div class="clear"></div>

    </form>
    <div style="color: red">
        {{ msg }}
        {% for k,err in user_login_form.errors.items %}
            {{ err }}
        {% endfor %}
    </div>
</div>
<script>

    $('#checkcode').click(function () {
        alert('刷新成功！')
        console.log('刷新成功！')
        $(this).attr('src', '{% url 'users:get_code' %}?ran=' + Math.random())
    })

</script>
</body>
</html>

jlfblog/templates/user_register.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
    <link href="{% static 'css/reglogin.css' %}" rel='stylesheet' type='text/css'/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div class="main">
    <div class="header">
        <h1>注册一个用户</h1>
    </div>
    <p></p>
    <form method="post" action="{% url 'users:user_register' %}">
        {% csrf_token %}
        <ul class="left-form">
            <h2>注册:</h2>
            <li>
                <input type="text" placeholder="用户名/邮箱" name="username"/>
                <a href="#" class="icon ticker"> </a>
                <div class="clear"></div>
            </li>
            <li>
                <input type="password" placeholder="密码" name="password"/>
                <a href="#" class="icon into"> </a>
                <div class="clear"></div>
            </li>
            <li>
                <input type="password" placeholder="确认密码" name="password1"/>
                <a href="#" class="icon into"></a>
                <div class="clear"></div>
            </li>
            <input type="submit" value="注册">
            <div class="clear"></div>
        </ul>
        <div class="clear"></div>

    </form>
    <div style="color: red">
        {{ msg }}
        {% for k,err in user_reform.errors.items %}
            {{ err }}
        {% endfor %}
    </div>
</div>

</body>
</html>